### ISSUE TITLE
Error when run the CLI unit-tests

### ISSUE THREAD

**Issue by anaimproove** [sfb2csolutionarchitects/b2c-crm-sync#100]
I am installing the connector and I am following the setup steps from the README.md file.
In the **Deployment Instructions** section, it says to run the command `npm run crm-sync:test:cli` but when I run it I get this error

![Error](https://user-images.githubusercontent.com/25003443/118824087-75340e00-b8b1-11eb-90c5-28f10877a890.png)

I am running the command in the root of the project (**b2c-crm-sync** folder) and my node version is v15.2.1.
I already deleted the node_modules folder and run the `npm install` command again, but it does not solve the problem.

If I jump this step and run the command `npm run crm-sync:test:b2c` it passes in all the 85 tests.
If I continue the documentation and run the command `npm run crm-sync:b2c:verify` then I get the same error as before.

![Error 2](https://user-images.githubusercontent.com/25003443/118824102-79f8c200-b8b1-11eb-827f-96b4798a3a26.png)

I don't know what am I missing.

**Comment by anaimproove** [comment]
I found out 2 wrong file names in the code. In master branch you should fix:
- in `b2c-crm-sync/lib/cli-api/_getRuntimeEnvironment.js` line 9, it should be `'../../lib/cli-api/_common/_getScratchOrgDurationDays')` instead of `'../../lib/cli-api/_common/_getScratchOrgDurationdays')`
- in `b2c-crm-sync/test/cli/cli-api/b2cCodeVersionsList.test.js` line 13, it should be `'../../../lib/cli-api/_b2cCodeVersionsList'` instead of `'../../../lib/cli-api/_b2cCOdeVersionsList'`

**Comment by b2csolutionarchitect** [comment]
@anaimproove -- thank you so much for logging this issue and sharing your feedback.  I'll be merging in your changes later this week.  If you can email me your contact details -- it would be my pleasure to send you an Architect Success hoody. :)

**Comment by b2csolutionarchitect** [comment]
... found both issues; thank you for your support with this.  Pushing the pull request now.
