### ISSUE TITLE
Restructure site-specific OCAPI Data API calls to leverage the v21.3 format for deployments.

### ISSUE THREAD

**Issue by b2csolutionarchitect** [sfb2csolutionarchitects/b2c-crm-sync#11]
### Issue Summary
Deployment to B2C Commerce is currently limited to OCAPI version v20.10 -- as v21 has changed its url format (with sites now included in the base of the URL vs near the end of the URL call).  We need to investigate what this change means:

- Do we not support legacy versions of OCAPI?
- Does this tie b2c-crm-sync specifically to v21.x moving forward?
- How do we provide backwards OCAPI compatibility (and to what degree)?

The solution should be dependent on clear answers to these questions.  Once that has been determined, we can move forward with how to create the OCAPI url structure to support the prioritized issue requirements.

**Comment by dhawal-p** [comment]
@b2csolutionarchitect, I have verified the below scenarios for bi-directional customer profile sync and they all are working as expected, so not sure if any of the points you mentioned above needs to be investigated unless there are specific steps to reproduce the issue. 

1. Upgrade from OCAPI v20.10 to v21.3:
- Setup and deploy B2C CRM Sync as is (OCAPI v20.10) and verify that Customer Sync is working as expected.
- Delete all the Contacts, Sites and Customer Lists from the ScratchOrg used in previous step. Change `OCAPI Version No` to v21_03 for the B2C Instance in the B2C CRM Sync app.
- Then did Seed Customer Lists and Sites, Activate B2C Customer Lists for the B2C Instance. Change `OCAPI Version No` to v21_03 for all the Sites and Customer Lists in the B2C CRM Sync app and verified that Customer Sync was working as expected.

2. Use OCAPI v21.3:
- Make required code changes to default to use OCAPI v21_03.
- Setup and deploy B2C CRM Sync. Verified that B2C Instance uses v21_03 as `OCAPI Version No` by default in the B2C CRM Sync app.
- I also did some manual verification of the bi-directional customer profile sync and it is working as expected.
- Used `npm run crm-sync:test:use-cases` to run all the unit-tests.
![image](https://user-images.githubusercontent.com/14078802/120272760-2ef88a80-c273-11eb-8a8b-cca7f9d14f7c.png)
![image](https://user-images.githubusercontent.com/14078802/120272644-0e303500-c273-11eb-83ed-f8c035bfc13e.png)

I have created PR https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/114 to upgrade OCAPI version to 21.3.

Thank you for your guidance on this @b2csolutionarchitect.

**Comment by b2csolutionarchitect** [comment]
Thank you @dhawal-p for your contribution!  We've rolled this into the [v0.9.0 release-branch](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/tree/release/0.9.0) and will include it in the code-base.
