### ISSUE TITLE
Error during crm-sync:test:use-cases

### ISSUE THREAD

**Issue by anandjpereira** [sfb2csolutionarchitects/b2c-crm-sync#126]
Encountered the following test failure and error on a Windows 10 dev environment while running npm run crm-sync:test:use-cases

.....
  46 passing (12m)
  1 failing

  1) Authenticating a B2C Customer Profile via the OCAPI Shop API
       does not allow updates to a SFDC Contact when sync-on-login is enabled and sync-once is enabled:
     Error: Request failed with status code 500
      at createError (node_modules\axios\lib\core\createError.js:16:15)
      at settle (node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:260:11)
      at IncomingMessage.emit (node:events:341:22)
      at endReadableNT (node:internal/streams/readable:1294:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21)

npm ERR! code 1
npm ERR! path C:\Users\xxx\yyy\b2c-crm-sync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "mocha "test/_use-cases/**/*.test.js""

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2021-06-13T10_00_17_358Z-debug.log

**Comment by b2csolutionarchitect** [comment]
Hi @anandjpereira -- thanks for logging your issue.  When you run the multi-cloud unit-tests against a B2C Commerce sandbox -- what you may experience intermittently are timeouts or 500 errors.  It looks like that's what you've got here.

> Error: Request failed with status code 500

I recommend re-running the multi-cloud unit tests.  If you continue to experience 500 errors, please do the following:

- Verify that you're running the latest version of our repo (v0.7.9).
- Verify that your environment is configured correctly by running `npm run crm-sync:sf:env:list`
- Verify that you can auth against your B2C Commerce sandbox by running `npm run crm-sync:sf:auth:usercreds`
- Verify your B2C Commerce configuration by running `npm run crm-sync:b2c:verify`

We've extended the multi-cloud unit tests to support multiple retries for http requests.  the [config/default.js](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/blob/master/config/default.js#L625) contains a variable we use to manage the total number of retries ([retryCount](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/blob/master/config/default.js#L625)) that defaults to three (3).  You can increase this if you want to support additional http-retries.

Thank you again for your issue -- and please reach out if you need additional support.  Hope and health to you, your team, and your family.

**Comment by b2csolutionarchitect** [comment]
... just re-read your issue and caught that you had 46 passes and a single failure.  Based on this, I think your configuration is good -- and for this specific unit test, you exceeded the retry count.  You can increase your retry-count, or execute the individual test-suite if you want to exercise the failed test.  Please reach out if you need anything else, ok?  Happy to support you.

**Comment by anandjpereira** [comment]
Thank you for the response. I will retest the 1 failure. My question was around the test ending gracefully.  The end output looks like this and will look into the code to find out if any of the steps in the test generated this message. Any insight here would help.

npm ERR! code 1
npm ERR! path C:\Users\xxx\yyy\b2c-crm-sync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "mocha "test/_use-cases/**/*.test.js""

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\xxx\AppData\Local\npm-cache_logs\2021-06-13T10_00_17_358Z-debug.log

**Comment by b2csolutionarchitect** [comment]
... this looks like an standard npm error and is reporting that the command failed.  If you scroll-up, you should see a mocha-specific error that provides some surface-level details for the test failure.  I don't think this is something you can / should want to edit.  I recommend leaving the npm output as-is, and scrolling up to see the mocha failure feedback provided.  The mocha feedback should tell you the specific class file and line-number of the assertion that failed.
