### ISSUE TITLE
In setup guide, filter logic is the same for Account/Contact and PersonAccount

### ISSUE THREAD

**Issue by sf-mrkpatchaa** [sfb2csolutionarchitects/b2c-crm-sync#127]
In the setup guide, this filter logic is the same for Account/Contacts and PersonAccounts
`1 OR (2 AND 3) OR (2 AND 4 AND 5) OR (2 AND 4) OR (4 AND 5 AND 6)`

But in the case of PersonAccount, I only see three conditions configured.
<img width="750" alt="Screenshot 2021-06-15 at 23 07 05" src="https://user-images.githubusercontent.com/52654550/122129765-79ab0280-ce2e-11eb-9069-06497d266474.png">

I used `1 OR (2 AND 3)` just to make sure I can activate the rule.

Is it a mistake in the setup guide or my scratch org was not configured well? 
Thanks.

**Comment by sf-mrkpatchaa** [comment]
Let me close this. I was looking at the wrong place :) 
Thanks @b2csolutionarchitect

**Comment by b2csolutionarchitect** [comment]
No worries -- great connecting with you.  As a reminder, we create the B2C Commerce: Person Account Duplicate Rule.  This rule maps Contact attributes to a PersonAccount via the associated match rule.  It looks like you were looking at the Standard Person Account Duplicate Rule.  

Thank you for closing the issue -- please reach out if you need anything else.  Happy to support you -- and thank you for your interest.
