### ISSUE TITLE
OOBO Customer Authenticator - Generate Wrong URL

### ISSUE THREAD

**Issue by luismiguelferreiraPWC** [sfb2csolutionarchitects/b2c-crm-sync#138]
I've passing the CRM Sync to my sandbox and I'm facing couples issues that I don't know if it's because anything is missing on the sandbox.

On the OOBO when I try to Order on Behalf a customer it generates this URL to give the customer authentication:

https://instace.sandbox.us01.dx.commercecloud.salesforce.com/s/-/dw/data/v20_10/sites/[[site-id-]]/s/[[site-id-]]/dw/shop/v20_10/customers/acAqsx1aH0i1DIFrX6Xfn9Q7KR/auth

It's this normal? From my understanding it's mixing the Data and Shop URLs, right?

He will get the domain on the Record API URL field of the Site which is: https://instance.sandbox.us01.dx.commercecloud.salesforce.com/s/-/dw/data/v20_10/sites/[[site-id]]

and If I remove this part '/s/-/dw/data/v20_10/sites/[[site-id]]' it's start working because the correct URL would be https://instace.sandbox.us01.dx.commercecloud.salesforce.com/s/[[site-id-]]/dw/shop/v20_10/customers/acAqsx1aH0i1DIFrX6Xfn9Q7KR/auth. Am I correct?

Even if I path this, when I click 'Launch Order on Behalf Of' it goes to a Salesforce page when it says 'URL No Longer Exists'.

Any help with this? Or maybe the best approach for deployments/integration or this into sandboxes?

**Comment by luismiguelferreiraPWC** [comment]
Hey @b2csolutionarchitect,

I don't know if you can see this image:

![image](https://user-images.githubusercontent.com/55134526/124268288-38ef0100-db31-11eb-808d-80ccb89b1f0c.png)

I think I found the issue. On the flow B2C Commerce: Order On Behalf Of: Contacts you have the wrong field on a Assignment variable during the sites loop. It should be Base_API_Url__c , but instead it's API_Url__c and this will cause issues on the OOBO when we have multiple sites.

I have updated and it's working now when I have one site or multiple sites.

**Comment by b2csolutionarchitect** [comment]
Thank you @luismiguelferreiraPWC -- I've made the fix, and will include this in our next build.  Stay tuned -- and thank you for your partnership. :)
