### ISSUE TITLE
Flow Error in "B2C Commerce: Schedule: B2C Client ID: AuthTokens" if no tokens are found.

### ISSUE THREAD

**Issue by sandragolden** [sfb2csolutionarchitects/b2c-crm-sync#146]
This is probably a rare use-case but there is an error in "B2C Commerce: Schedule: B2C Client ID: AuthTokens" when there are no expired/invalid tokens to delete.

GET RECORDS: recGet_expiredAuthTokens
Find all B2C_AuthToken__c records where:
1. B2C_Client_ID__c Equals {!$Record.Id} (a0203000001s6S1AAI)
2. Is_Expired__c Equals true
3. Is_Valid__c Equals false
with advanced logic (1 AND (2 OR 3))
Sort records by: Expiration_Date__c (Ascending)
Store the values of these fields in recGet_expiredAuthTokens: Id
Result
Failed to find records.

DELETE RECORDS: recDel_b2cAuthTokens
Delete B2C_AuthToken__c records whose IDs are stored in {!recGet_expiredAuthTokens}.
Variable Values
None.
Result
Failed to delete records whose IDs are in {!recGet_expiredAuthTokens}.

**Comment by b2csolutionarchitect** [comment]
... this has been addressed as part of the 0.9.0 release-branch.  Thank you @sandragolden! :)
