### ISSUE TITLE
Make the number of days a scratchOrg will live configurable prior to deployment.

### ISSUE THREAD

**Issue by b2csolutionarchitect** [sfb2csolutionarchitects/b2c-crm-sync#22]
### Issue Summary
Currently, scratchOrgs are created with a TTL of seven days (by default).  That said, scratchOrgs can live up to 30 days.  When we spin-up a scratchOrg, the CLI arguments can include an alternative TTL.  Let's embed that either in the config.js or .env file(s).

**Comment by sandragolden** [comment]
I've submitted PR #23 for this enhancement. Please let me know of any adjustments needed. tested using command line and the `npm run crm-sync:sf:build` command and both seem to pull in and correctly set the duration days.

**Comment by b2csolutionarchitect** [comment]
... thank you @sandragolden -- this is fantastic!  Let me review your PR over the weekend and I'll get you feedback.  Congratulations on being the first non-Salesforce PR for crm-sync. We appreciate your contribution and can't wait to see a picture of you in your hoodie on Instagram :)
