### ISSUE TITLE
Address Apex Unit Test coverage gaps to enable deployability to production environments.

### ISSUE THREAD

**Issue by b2csolutionarchitect** [sfb2csolutionarchitects/b2c-crm-sync#28]
### Issue Summary
Currently, our unit test coverage for Apex classes sits at 61%.  This is well below the [75% required](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_code_coverage_intro.htm#:~:text=The%20Apex%20testing%20framework%20generates,run%20one%20or%20more%20tests.&text=To%20deploy%20Apex%20or%20package,and%20those%20tests%20must%20pass.) for production deployments.

> The Apex testing framework generates code coverage numbers for your Apex classes and triggers every time you run one or more tests. ... To deploy Apex or package it for the Salesforce AppExchange, unit tests must cover at least 75% of your Apex code, and those tests must pass.

![image](https://user-images.githubusercontent.com/42348993/114303535-8d3b9500-9a9c-11eb-8f51-41bcbaf01bb1.png)

Let's review the existing suite of tests, address failures, and expand the coverage so that we hit production-deployment and AppExchange thresholds.  None of this works if we can't deploy our code in a trustworthy manner.

**Comment by b2csolutionarchitect** [comment]
... re-opening to help drive another-round of unit-test coverage improvements.

**Comment by beuktv** [comment]
@b2csolutionarchitect  Can I get access to a sandbox copy?  I can take a look at creating the test classes

**Comment by b2csolutionarchitect** [comment]
... we've extended our Apex unit-tests to provide 90% test-coverage.  This has been included in the [v0.9.0 release-branch](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/tree/release/0.9.0).
