### ISSUE TITLE
Scratch org Deployment Fails when B2C site ID has non-alphanumeric characters

### ISSUE THREAD

**Issue by GuinnM07** [sfb2csolutionarchitects/b2c-crm-sync#47]
### Issue Summary
The naming restrictions for the SF connected application names are more strict than the restrictions on a B2C Commerce site. For instance, I have sites that use dashes: sitename-us and sitename-uk

The deployment command "npm run crm-sync:sf:build" fails with the following error message: "Name: The Connected Application API Name can only contain underscores and alphanumeric characters. It must be unique, begin with a letter, not include spaces, not end with an underscore, and not contain two consecutive underscores."

### Success Criteria
This issue will be considered completed when the following items have been completed:

- [x] ensure that the connectApp name begins with a letter
- [x] prevent any spaces / whitespace from being included in the connectedApp name
- [x] do not allow the connectedApp name to allow underscores at the end
- [x] do not allow the connectedApp name to include two consecutive underscores
- [x] only allow alpha-numeric characters in the connectedApp Name
- [x] author a simple unit-test that exercises the connectedApp validator

**Comment by beuktv** [comment]
@GuinnM07 @b2csolutionarchitect Hi!  I don't know much about GitHub and I barely have SFDX on my Mac, but SF Core will not accept those characters.  I don't think there is an API to call to make Salesforce convert it, so you have to make sure the sitename adheres before you submit to SF.    I wrote this is Ruby to strip out dashes, underscores, spaces to a Sitename before it gets submitted.  Do this before calling SF and you will have fewer errors.


`# Pass a name to this command like:
# ruby hello_world.rb "I am a Name with Dashes -- and ** Other stuff"
# output>IamaNamewithDashesandOtherstuff


#  You can pass in multiple strings, do each one in quotes
ARGV.each do|a|
puts "You passed in Argument: #{a}"

if a  =~ /^[A-Z0-9]+$/i
         puts "Subject is alphanumeric"
else
        puts "Subject is not alphanumeric, let me change it for you"
        a = a.gsub(/[^a-zA-Z0-9]/,"")
        puts a
end

end
`

**Comment by b2csolutionarchitect** [comment]
... thank you @beuktv and @GuinnM07; actually working on this now and will try to knock this out quickly.  Look for an update from me later today -- I don't think this will take long.  Thank you both for bringing this up -- really appreciate your communication and contributions. :)

**Comment by beuktv** [comment]
@b2csolutionarchitect #hoodyworthy ??? ;)

**Comment by GuinnM07** [comment]
Thanks @b2csolutionarchitect I'll check it out Monday
