### ISSUE TITLE
Update the .env documentation to explain formatting constraints on the B2C Instance Name property.

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#59]
### Issue Summary
The b2cInstanceName can only contain underscores and alphanumeric characters. We need to clearly mention this in our documentation -- and correct the sample .env file example.

> Change b2csandbox-017a to b2csandbox_017a -- as this is misleading to developers / architects

**Comment by b2csolutionarchitect** [comment]
... we found a bug in our environment validation logic that was not correctly evaluating errors.  We've corrected the issue, and now output validation errors that can impede deployment processing:

![image](https://user-images.githubusercontent.com/42348993/121593322-c8f5cb00-ca09-11eb-81ce-60f55fb9343a.png)

> We're going to enforce the the b2cInstanceName property only allow letters and numbers.  If environmentValidation fails -- it will prevent any deployment activities from being performed in the local environment.

**Comment by anandjpereira** [comment]
Instance naming convention for SFCC on-demand sandboxes has a hyphen. 
example - <realmID>-<sequence>.sandbox.us01.dx.commercecloud.salesforce.com
bxdt-001.sandbox.us01.dx.commercecloud.salesforce.com

Is there a way to change the host name to avoid this issue?

**Comment by b2csolutionarchitect** [comment]
This issue has been addressed and included in the [v0.9.0 release-branch](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/tree/release/0.9.0).
