### ISSUE TITLE
Refactor the B2C Commerce setup documentation and call-out that the multi-cloud unit-tests are dependent on RefArch and RefArchGlobal having their own customerLists.

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#61]
### Issue Summary
In our readMe.md, we don't mention multiple customerLists until the testing phase of the deployment process.  Let's move this into the configuration section so that all of the B2C Commerce configuration documentation is in one section.

> This is the documentation that should be moved upward in the B2C Commerce setup section of the readMe.

The multi-cloud unit-tests are designed to exercise your B2C Commerce Sandbox and Salesforce Platform ScratchOrg via REST APIs to validate the installation is successful.  The B2C Commerce interactions are dependent on the deployment of the RefArch and RefArchGlobal sites. Each site should be associated to its own separate CustomerList.

⚠️   Do not associate both sites to the same CustomerList -- as this will cause tests dependent on multiple customer-lists to fail.   ⚠️"

**Comment by b2csolutionarchitect** [comment]
... deleted as part of #67; see that PR for details.
