### ISSUE TITLE
test use cases

### ISSUE THREAD

**Issue by inesmverissimo** [sfb2csolutionarchitects/b2c-crm-sync#84]
Hi, I am having problems at the end of the configuration (base scratch profile), running `npm run crm-sync:test:use-cases`

<img width="1108" alt="errors1" src="https://user-images.githubusercontent.com/67901265/117641098-ac9e0e80-b17d-11eb-9c86-46df441c533e.png">
<img width="1084" alt="errors2" src="https://user-images.githubusercontent.com/67901265/117641108-af98ff00-b17d-11eb-9c77-99332d3c6cd1.png">
<img width="877" alt="errors3" src="https://user-images.githubusercontent.com/67901265/117641114-b162c280-b17d-11eb-9807-313eb6249460.png">

The log file:
<img width="1257" alt="log_file" src="https://user-images.githubusercontent.com/67901265/117641156-bde71b00-b17d-11eb-8e7f-da3328b232d7.png">

Has anyone faced this problem?
Thank you in advance

**Comment by b2csolutionarchitect** [comment]
... hi @inesmverissimo -- thank you for submitting an issue.  So candidly, sometimes the B2C Commerce sandboxes can be a little temper-mental with OCAPI requests.  I've personally run into issues where the 500 errors impede test execution.  That said, here are the things I do when debugging environments:

- Next, enable custom logs in your sandbox.  Raise the default debug-level to `DEBUG` -- as b2c-crm-sync will render custom log files that audit everything it does.  To test and troubleshoot, we have to see what's happening first.
- Next, clear the custom cache for your storefront(s).  We use the B2C Commerce Custom Cache to store the authToken generated by your scratchOrg.  If you're experiencing challenges authenticating -- clear the cache and let a new token generate.

When you're executing the unit tests, consider running just one test or a sub-set of tests vs the entire library.  What I like to do is execute the following:

**Comment by b2csolutionarchitect** [comment]
... hi @inesmverissimo -- I wanted to check-in with you and see if you are still experiencing issues with the setup of b2c-crm-sync.  Don't hesitate to reach out, and looking forward to hearing from you.  Hope and health to you and your family.

**Comment by inesmverissimo** [comment]
Thank you @b2csolutionarchitect .  I run the commands successfully and each test but still have the same error. I give up from the base scratch profile, so I've cloned the code again and tried to configure with person account, but I am having trouble too.
```
"error": "SortOrder must be in sequential order from 1.",
 "fullName": "PersonAccount.Standard_Person_Account_Duplicate_Rule",
 "type": "DuplicateRule",
```
I have the code up to date.

**Comment by aelzayady** [comment]
I do get the same error too.

**Comment by b2csolutionarchitect** [comment]
... hi @inesmverissimo -- I just pushed some updates to the CLI unit-tests that were preventing their successful execution.  I recommend that you pull this code and try again.  One scenario that can cause the multi-cloud unit tests to fail is not setting-up the B2C Instance in your scratchOrg.  Please confirm that you have that configured -- and don't hesitate to reach out if you need anything else.

I was able to successfully build an environment using the base and personaccounts scratchOrg profiles with this release.  That said, please share if you continue to run into any issues -- happy to support you.
