### ISSUE TITLE
Creating new scratch org overtime you deploy

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#93]
We need a way to reuse an existing scratch org instead of creating a new one overtime we want to deploy. In my case, I am testing IDP integration on the same scratch org and try to connect the process with crm-sync & deploying a new fix for crm sync, means a new scratch org will be created and I have to copy over all my configurations to the new scratch org.

Hint - I do understand a scratch org is limited to just 30 days :)

**Comment by b2csolutionarchitect** [comment]
Hi @aelzayady -- so, b2c-crm-sync won't handle re-deployments to scratchOrgs.  If you want to create a new instance, we recommend spinning-up a new scratchOrg and deploying using our CLI tooling.  If, however, you want to deploy changes that you make to an existing scratchOrg (ex. customizations that are project specific or extensions beyond the core features of b2c-crm-sync), then you should leverage the `force:source` [SFDX command-set](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source).

SFDX was specifically designed to solve incremental meta-data deployments to scratchOrgs via the following commands:

- [force:source:push](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_push)
> Pushes changed source from your project to a scratch org to keep them in sync.

- [force:source:pull](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_pull)
> Pulls changed source from the scratch org to your project to keep them in sync.

- [force:source:retrieve](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_retrieve)
> Retrieves metadata in source format from an org to your local Salesforce DX project.

- [force:source:deploy](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_deploy)
> Deploys metadata in source format to an org.

You can use these commands to deploy and retrieve tracked changes to / from your scratchOrg, or deploy ad-hoc meta-data independently of tracked changes.  If you want to deploy future changes to your scratchOrg -- you should leverage SFDX.  If you want to deploy new b2c-crm-sync code to an existing scratchOrg, I recommend you create a new scratchOrg and use the `crm-sync:b2c:build` command to re-wire the integration from B2C Commerce to your new scratchOrg.

> You can deploy deltas of b2c-crm-sync Salesforce Platform assets between updates.  To do this, though, you'll have to identify the deltas by comparing instances of the master branch -- and then leverage SFDX to deploy those changes individually.

**Comment by aelzayady** [comment]
Thanks @b2csolutionarchitect makes sense
