### ISSUE TITLE
0BZo0000000KyjG Sandbox: Error Occurred During Flow "B2CCommerce_PlatformEvent_ProcessContactUpdate"

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#94]
This error happens a lot while running test cases

Error element ia_retrieveB2CCommerceCustomerProfile (FlowActionCall).
An Apex error occurred: System.CalloutException: The URI is invalid.
Flow Details
Flow API Name: B2CCommerce_PlatformEvent_ProcessContactUpdate
Type: Autolaunched Flow
Version: 1
Status: Active
Org: b2c-crm-sync (00D54000000MkFc)
Flow Interview Details
Interview Label: B2C Commerce: Platform Event: Process Contact: 5/18/2021, 9:37 AM
Current User: User User (00554000007tfCt)
Start time: 5/18/2021, 9:37 AM
Duration: 0 seconds
How the Interview Started
User User (00554000007tfCt) started the flow interview.
API Version for Running the Flow: 51
Some of this flow's variables were set when the interview started.
$Record = B2C_Commerce_ProcessCustomerDetails__e (No ID)
DECISION: dec_isProcessModeValid
Skipped this outcome because its conditions weren't met: decOutcome_ProcessModeIsInValid
Outcome conditions:
1. {!$Record.Process_Mode__c} (retrieve) Does not equal retrieve
2. {!$Record.Process_Mode__c} (retrieve) Does not equal publish
Logic: All conditions must be true (AND)

Default outcome executed.
GET RECORDS: recGet_Contact
Find all Contact records where:
Id Equals {!$Record.CRM_Contact_ID__c} (0035400000hDsPMAA0)
Store the values of these currently referenced fields in recGet_Contact: AccountId, Id
Because recGet_Contact is passed to an action, subflow, or Lightning component, store the values of all Contact fields that the running user has access to.
Result
Successfully found records.
DECISION: dec_verifyContactWasFound
Outcome executed: decOut_ContactWasVerfiied
Outcome conditions:
{!$Record.CRM_Contact_ID__c} (0035400000hDsPMAA0) Equals {!recGet_Contact.Id} (0035400000hDsPMAA0)
DECISION: dec_doesContactHaveParentAccount
Skipped this outcome because its conditions weren't met: decOut_ContactDoesNotHaveParentAccount
Outcome conditions:
{!recGet_Contact.Account.Id} (0015400000gCMwFAAW) Equals true

Default outcome executed.
GET RECORDS: recGet_B2CCustomerList
Find all B2C_CustomerList__c records where:
Id Equals {!$Record.CRM_CustomerList_ID__c} (a0154000007cGaUAAU)
Store the values of these currently referenced fields in recGet_B2CCustomerList: Id, B2C_Instance__c
Because recGet_B2CCustomerList is passed to an action, subflow, or Lightning component, store the values of all B2C_CustomerList__c fields that the running user has access to.
Result
Successfully found records.
GET RECORDS: recGet_B2CInstance
Find all B2C_Instance__c records where:
Id Equals {!recGet_B2CCustomerList.B2C_Instance__c} (a025400000TrMAWAA3)
Store the values of these currently referenced fields in recGet_B2CInstance: Id
Because recGet_B2CInstance is passed to an action, subflow, or Lightning component, store the values of all B2C_Instance__c fields that the running user has access to.
Result
Successfully found records.
B2CIAVALIDATECONTACT (APEX): ia_validateIntegrationConfiguration
Inputs:
b2cInstance = {!recGet_B2CInstance} (B2C_Instance__c (a025400000TrMAWAA3))
contact = {!recGet_Contact} (Contact (0035400000hDsPMAA0))
customerList = {!recGet_B2CCustomerList} (B2C_CustomerList__c (a0154000007cGaUAAU))
processMode = {!$Record.Process_Mode__c} (retrieve)
Outputs:
b2cInstance (B2C_Instance__c (a025400000TrMAWAA3))
allowIntegrationProcess (true)
isCustomerListActive (true)
isProfileRetrievalEnabled (true)
configurationMessage (null)
contact (Contact (0035400000hDsPMAA0))
isContactIntegrationDisabled (false)
isContactUpdateEnabled (true)
customerList (B2C_CustomerList__c (a0154000007cGaUAAU))
processMode (retrieve)
isInstanceActive (true)
isProfilePublishingEnabled (true)
isContactCreationEnabled (true)
DECISION: dec_isIntegrationEnabledForPlatformEvent
Skipped this outcome because its conditions weren't met: decOut_integrationIsDisabled
Outcome conditions:
{!ia_validateIntegrationConfiguration.allowIntegrationProcess} (true) Equals false

Default outcome executed.
DECISION: dec_RetrieveOrPublishB2CCustomerProfiles
Outcome executed: decOutcome_retrieveB2CCustomerProfile
Outcome conditions:
{!$Record.Process_Mode__c} (retrieve) Equals retrieve
B2CIAGETCUSTOMERPROFILE (APEX): ia_retrieveB2CCommerceCustomerProfile
Inputs:
apiVersion = {!$Record.OCAPI_Version_Number__c} (v20_10)
b2cCustomerListId = {!$Record.B2C_CustomerList_ID__c} (RefArch)
b2cCustomerNo = {!$Record.B2C_Customer_No__c} (00001065)
crmContactId = {!$Record.CRM_Contact_ID__c} (0035400000hDsPMAA0)
crmCustomerListId = {!$Record.CRM_CustomerList_ID__c} (a0154000007cGaUAAU)
namedCredential = {!$Record.Named_Credential__c} (bggl_036_ahmed: B2C: Client Credentials)
Error Occurred: An Apex error occurred: System.CalloutException: The URI is invalid.

**Comment by aelzayady** [comment]
![Screenshot 2021-05-19 at 9 32 35 am](https://user-images.githubusercontent.com/39186028/118781625-2c666000-b885-11eb-8473-63c5ae364546.png)
![Screenshot 2021-05-19 at 9 31 57 am](https://user-images.githubusercontent.com/39186028/118781629-2d978d00-b885-11eb-9b91-4f13de7b8e5b.png)

**Comment by aelzayady** [comment]
Both B2C & CRM configurations are done right so don't know what is triggering the errors. btw, I am using PersonAccount.

**Comment by b2csolutionarchitect** [comment]
@aelzayady -- it's very hard to tell what's failing here without seeing a log file.  What I think is happening is this:

- The process is working as expected
- The logic to generate the platformEvent is successfully invoked
- When the REST API callout to B2C Commerce is made, the call is failing because the URI is invalid

```bash
B2CIAGETCUSTOMERPROFILE (APEX): ia_retrieveB2CCommerceCustomerProfile
Inputs:
apiVersion = {!$Record.OCAPI_Version_Number__c} (v20_10)
b2cCustomerListId = {!$Record.B2C_CustomerList_ID__c} (RefArch)
b2cCustomerNo = {!$Record.B2C_Customer_No__c} (00001065)
crmContactId = {!$Record.CRM_Contact_ID__c} (0035400000hDsPMAA0)
crmCustomerListId = {!$Record.CRM_CustomerList_ID__c} (a0154000007cGaUAAU)
namedCredential = {!$Record.Named_Credential__c} (bggl_036_ahmed: B2C: Client Credentials)
Error Occurred: An Apex error occurred: System.CalloutException: The URI is invalid.
```

I recommend turning on debug logs within your Salesforce scratchOrg so that automation processes are logged.  This should give you a line number for where in the B2CIAGETCUSTOMERPROFILE class the failure is occurring.  My guess is that this is related to the namedCredential: 

- Confirm that the namedCredential is valid and authenticated against Account Manager
- Verify that [no special characters exist](https://help.salesforce.com/articleView?id=sf.named_credentials_define.htm&type=5) in the namedCredential developerName.

Please remember that the namedCredential is being pulled from the CustomerList record and embedded in the HTTP Callout used to invoke the B2C Commerce REST APIs.  If the namedCredential developerName assigned to the customerList does not  directly map to an established namedCredential -- the HTTP callout will fail.  `The URI is invalid` error message is a little misleading here -- as the HTTP Callout URL is likely valid, but the invalid namedCredential invalidates the url.
