### ISSUE TITLE
Enhance crm-sync to support Oauth2 login

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#95]
Currently the CRM sync process works (triggered only) when you login to Commerce but it is not integrated with Oauth-Reentry controller so it doesn't get triggered with this particular flow. I suggest we support it.

**Comment by jbachelet** [comment]
Hey @aelzayady,

Thank you for opening this improvement request. Please find the implementation of this in PR#110.
Can you please have a look and tell us if this fits your need?

Thanks again!

**Comment by aelzayady** [comment]
@jbachelet Looks like the right thing :) is it going to differentiate or work with IDP too? Flow needs to be bit different if this third part is actually Salesforce IDP as the account is already created on service cloud side so basically you just need to sync profile rather than trying to create it on service cloud side.

**Comment by b2csolutionarchitect** [comment]
@jbachelet and @aelzayady -- I love this topic and I'm very passionate about tackling Salesforce IDP and incorporating it into b2c-crm-sync as another avenue to operationalize our data strategy and simplify the effort to integrate our two platforms.  I'd like this to be the next priority I focus on after delivering OOBO, streamlining the deployment to a non-scratchOrg environment, and bringing our documentation up to par with the capabilities of the project.

I 100% agree that we need this, and we should use it to differentiate Salesforce IDP from others.  It will be good to also incorporate SLAS in this as well, as we can use the USID as one of the identifiers we anchor to as part of our resolution rules.

**Comment by aelzayady** [comment]
@jbachelet There were some minor fixes I had to do in oauth2 controller on commerce itself to make it work (which is not related to crm-sync) but once those were sorted out, crm-sync worked just fine with Salesforce IDP. The PersonAccount is already created in advance on salesforce, then when I tried to login, I noticed Crm-sync managed to find the account on service cloud & made the right associations.

**Comment by aelzayady** [comment]
If you need a copy from those fixes in Oauth2-reentry controller, please let me know. I think I kind of need to open this defect against SFRA.

**Comment by jbachelet** [comment]
@aelzayady please send me those fixes by email at jbachelet@salesforce.com. This will help me to understand what the gap in SFRA is.
If I understand correctly, the PR associated with this ticket is not needed anymore, or should we still keep it?
