### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#97]
I do get this error consistently when executing test cases and I can't find the root cause.

![Screenshot 2021-05-19 at 9 41 16 am](https://user-images.githubusercontent.com/39186028/118782891-74d24d80-b886-11eb-855d-81674a87c62e.png)
![Screenshot 2021-05-19 at 9 32 35 am](https://user-images.githubusercontent.com/39186028/118782901-7734a780-b886-11eb-9fdf-6df7de42cba9.png)
![Screenshot 2021-05-19 at 9 31 57 am](https://user-images.githubusercontent.com/39186028/118782905-77cd3e00-b886-11eb-98d0-f99e0bb36543.png)

**Comment by aelzayady** [comment]
My configurations looks right given what is above, so don't know what might be missing.

**Comment by b2csolutionarchitect** [comment]
@aelzayady -- please see #98 for guidance on how to provide more information regarding these failures.  We can't support you with this level of information.  That said, if you can provide us details from your B2C Commerce log files -- we should be able to provide you with guidance to complete your configuration.

**Comment by b2csolutionarchitect** [comment]
... the root cause for this issue is #117.  Associating this issue to the upcoming v0.8.0 PR.
