### ISSUE TITLE
Order on behalf is not working despite of configuration looks right

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#99]
I tried to review everything around order on behalf and all configurations looks right but still it is not working. I am sure I have named credentials assigned properly as well as client id. 

![Screenshot 2021-05-19 at 9 47 30 am](https://user-images.githubusercontent.com/39186028/118783809-5587f000-b887-11eb-96ff-93296a096991.png)
![Screenshot 2021-05-19 at 9 46 41 am](https://user-images.githubusercontent.com/39186028/118783814-56b91d00-b887-11eb-9965-ed2a82628887.png)
![Screenshot 2021-05-19 at 9 46 17 am](https://user-images.githubusercontent.com/39186028/118783818-5751b380-b887-11eb-9839-bc599f863a94.png)
![Screenshot 2021-05-19 at 9 46 04 am](https://user-images.githubusercontent.com/39186028/118783821-57ea4a00-b887-11eb-8101-1f4083177f19.png)

![Screenshot 2021-05-19 at 9 32 35 am](https://user-images.githubusercontent.com/39186028/118783825-591b7700-b887-11eb-8238-899729c14376.png)
![Screenshot 2021-05-19 at 9 31 57 am](https://user-images.githubusercontent.com/39186028/118783826-59b40d80-b887-11eb-8e57-b51c2caf8a0d.png)

**Comment by b2csolutionarchitect** [comment]
@aelzayady -- the startUp page for b2c-crm-sync includes instructions on how to setup OOBO.  There's a couple of things to consider reviewing:

1. Make sure that you setup the anonymous OOBO Customer and include their customerId / customerNo in the site definition (you currently have those fields blank in your site definition).
2. Confirm that you have created the per-user namedCredential representing the serviceAgent with OOBO rights.

The messaging can be improved -- but I believe what is being reported here is correct.  The customer information isn't populated, and the namedCredential may not exist.  We're in the process of revamping this (see #82 for details) -- and simplifying the setup experience.  That said, we should have this available within the week.  Should you need anything in the meantime, please feel free to connect with me at your convenience.
